<center></center

<center><h1><b>Derivatives & Matrix</b><h1/></center>

Derivates are used for non linear equations while slope is used for linear equations. Derivates are slopes with curves. This makes it to be function. Slope is a constant.

There is alos partial derivative. This is done by applying the derivative function to just one part of the equation.

## Matrix

Matrix is the araangement of numbers in 2 dimension.
dot product is multiplication of two vectors. A vector is 1 dimensional data.

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
import numpy as np

In [4]:
revenue = np.array([[180, 200, 220], [24, 36, 40], [12, 18, 20]])
expenses = np.array([[80, 90, 100], [10, 16, 20], [8, 10, 10]])

In [5]:
revenue

array([[180, 200, 220],
       [ 24,  36,  40],
       [ 12,  18,  20]])

In [6]:
expenses

array([[ 80,  90, 100],
       [ 10,  16,  20],
       [  8,  10,  10]])

In [7]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

### Dot Product

In [8]:
price_per_unit = np.array([1000, 400, 1200])
units = np.array([[30, 40, 50], [5, 10, 15], [2, 5, 7]])

In [9]:
# The equation below will make numpy to perform Broadcasting function 
total_revenue = price_per_unit * units
total_revenue

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [10]:
# The dot product calculation
total_revenue = np.dot(price_per_unit, units)
total_revenue

array([34400, 50000, 64400])

### Exercise

In [16]:
revenue_dollars = np.array([[200, 220, 250], [68, 79, 105], [110, 140, 180], [80, 85, 90]])
exchange_rate = np.array([75])

In [14]:
revenue_dollars

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

In [17]:
amount = revenue_dollars * exchange_rate
amount

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [18]:
flower = np.array([[50, 60, 25], [10, 13, 5], [40, 70, 52]])
price = np.array([20, 30, 15])

In [19]:
flower

array([[50, 60, 25],
       [10, 13,  5],
       [40, 70, 52]])

In [20]:
total_price = np.dot(flower, price)
total_price

array([3175,  665, 3680])