<center><h1><b>Neural Network Gradient Descent</b></h1></center>

Gradient descent is used to find out the relationship between values in a linear equation. It also known as prediction function

 x-----y
 
 2-----7
 
 3-----9
 
y = x * 2 + 3

2 ----> is Weight

3 ----> is Bias

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import seaborn as sb

from sklearn.model_selection import train_test_split

%matplotlib inline

In [3]:
data = {'age': [22,25, 47, 52, 46, 56, 40, 55, 60, 62, 61, 18, 28, 27, 29, 49, 55, 25, 58, 19, 18, 21, 26, 40, 45, 50, 54, 23],
       'affordability': [1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1],
       'bought_insurance': [0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0]}

In [4]:
df = pd.DataFrame(data)
df.head()

age  affordability  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [5]:
df.shape

(28, 3)

In [6]:
df.describe().T

count       mean        std   min   25%   50%    75%   max
age                28.0  39.678571  15.451366  18.0  25.0  42.5  54.25  62.0
affordability      28.0   0.642857   0.487950   0.0   0.0   1.0   1.00   1.0
bought_insurance   28.0   0.500000   0.509175   0.0   0.0   0.5   1.00   1.0

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df[['age', 'affordability']], df['bought_insurance'], test_size=0.2, random_state=0)

In [8]:
X_train.shape

(22, 2)

In [9]:
X_test.shape

(6, 2)

 ### Scaling of age
 
 Scaling makes machine learning to work better

In [10]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [11]:
X_train_scaled.head()

age  affordability
24  0.45              1
13  0.27              0
20  0.18              1
25  0.50              1
16  0.55              1

In [12]:
from keras import Input

model = keras.Sequential([
    Input(shape=(2,)),  # input layer
    keras.layers.Dense(1, activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=650)


Epoch 1/650
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 723ms/step - accuracy: 0.5000 - loss: 0.6904
Epoch 2/650
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.6900
Epoch 3/650
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.6897
Epoch 4/650
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.6893
Epoch 5/650
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.6889
Epoch 6/650
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.6885
Epoch 7/650
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.6882
Epoch 8/650
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.6878
Epoch 9/650
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5000 - loss: 0.6874
Epoch 10/650
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5000 - loss: 0.6870
Epoch 11/650
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5000 - loss: 0.6867
Epoch 12/650
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5000 - l

In [13]:
## model evaluation
model.evaluate(X_test_scaled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.6667 - loss: 0.6177


[0.6177311539649963, 0.6666666865348816]

In [14]:
X_test_scaled

age  affordability
2   0.47              1
22  0.26              0
14  0.29              0
17  0.25              0
5   0.56              1
11  0.18              1

In [15]:
# Making prediction
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step


array([[0.66404796],
       [0.43226305],
       [0.43886065],
       [0.43006906],
       [0.68176514],
       [0.6039535 ]], dtype=float32)

In [16]:
y_test

2     1
22    0
14    0
17    1
5     1
11    0
Name: bought_insurance, dtype: int64

### Knowing the Final Weight and Bias

In [17]:
coef, intercept = model.get_weights()
coef

array([[0.8945529],
       [0.7661537]], dtype=float32)

In [18]:
intercept

array([-0.50520766], dtype=float32)

## Building the Model with Python Without TensorFlow

In [19]:
def sigmoid(x):
    import math
    return 1 / (1 + math.exp(-x))

In [20]:
sigmoid(18)

0.9999999847700205

In [21]:
def prediction_function(age, affordability):
    weighted_sum = coef[0] * age + coef[1] * affordability + intercept
    return sigmoid(weighted_sum)

In [22]:
prediction_function(.47, 1)

/tmp/ipykernel_21400/3918314859.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.6640479400658207

In [23]:
# Putting the log loss in a function

def log_loss(y_true, y_predicted):
    import numpy as np
    epsilon = 1e-15
    # Clip the predicted values between epsilon and 1 - epsilon
    y_predicted_new = np.clip(y_predicted, epsilon, 1 - epsilon)
    # Log loss calculation
    return -np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))


In [24]:
def sigmoid_numpy(x):
    return 1/(1 + np.exp(-x))

In [25]:
sigmoid_numpy(np.array([12, 0, 1]))

array([0.99999386, 0.5       , 0.73105858])

In [26]:
# Gradient descen function to find weight
def gradient_descent(age, affordability, y_true, epochs, loss_threshold):
    # w1, w2, bias will be generated
    w1 = w2 = 1 
    bias = 0
    rate = 0.5
    n = len(age)
    
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        
        loss = log_loss(y_true, y_predicted)
        
        # Weight 1 derivative
        w1d = (1/n) * np.dot(np.transpose(age), (y_predicted - y_true))
        # Weight 2 derivative
        w2d = (1/n) * np.dot(np.transpose(age), (y_predicted - y_true))
        
        # Bias derivative
        bias_d = np.mean(y_predicted - y_true)
        
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d
        
        print(f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
        
        if loss <= loss_threshold:
            break
    
    return f'w1:{w1}, w2:{w2}, bias:{bias}'
        

In [31]:
gradient_descent(X_train_scaled['age'], X_train_scaled['affordability'], y_train, 650, 0.5925)

Epoch:0, w1:0.976400033722807, w2:0.976400033722807, bias:-0.11929523268087014, loss:0.6904170412461691
Epoch:1, w1:0.9582784009183538, w2:0.9582784009183538, bias:-0.2251155797143852, loss:0.6605397752323087
Epoch:2, w1:0.9451981496598241, w2:0.9451981496598241, bias:-0.31856873438473465, loss:0.6376245637624881
Epoch:3, w1:0.9366491983924986, w2:0.9366491983924986, bias:-0.4009260596055467, loss:0.6202003067089075
Epoch:4, w1:0.9320952598472109, w2:0.9320952598472109, bias:-0.4735101172312454, loss:0.6069797302785039
Epoch:5, w1:0.9310094993626791, w2:0.9310094993626791, bias:-0.5376106297190913, loss:0.5969018366496534
Epoch:6, w1:0.9328980535480693, w2:0.9328980535480693, bias:-0.5944301080160043, loss:0.5891309461017252


'w1:0.9328980535480693, w2:0.9328980535480693, bias:-0.5944301080160043'

In [28]:
coef, intercept

(array([[0.8945529],
        [0.7661537]], dtype=float32),
 array([-0.50520766], dtype=float32))

In [29]:
 w1 = 0.9328980535480693, w2 = 0.9328980535480693, bias = -0.5944301080160043 