<center>
    <h1><b> K- Fold Cross Validation</b></h1>
</center>

This is a method used to correct over-fittig. The whole dataset is divided into different parts or folds and each section of each part is used to test that particular part. The score values for each part or fold is then averaged. This operatio is done by using K-Fold API


In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.model_selection import train_test_split, KFold, StratifiedKFold  # stratified seems better because it divides dataset uniformly
from sklearn.model_selection import cross_val_score  # This is the best API to use for cross validation
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.datasets import load_digits


%matplotlib inline

In [3]:
digits = load_digits()

In [4]:
 X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3, random_state= 0)

In [10]:
lr = LogisticRegression(max_iter = 2000)

In [11]:
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9555555555555556

In [14]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9907407407407407

In [17]:
rf = RandomForestClassifier(n_estimators = 40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9703703703703703

## Using K-Fold Cross Validation

In [19]:
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [27]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [28]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return(model.score(X_test, y_test))

In [30]:
get_score(LogisticRegression(max_iter = 2000), X_train, X_test, y_train, y_test)

0.9555555555555556

In [31]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9907407407407407

## Using Stratified KFold

In [33]:
folds = StratifiedKFold(n_splits = 3) 

In [44]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(max_iter = 5000), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators = 40), X_train, X_test, y_train, y_test))

    

In [45]:
scores_l

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]

In [46]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [47]:
scores_rf

[0.9332220367278798, 0.9565943238731218, 0.9198664440734557]

In [52]:
cross_val_score(LogisticRegression(max_iter = 5000), digits.data, digits.target, cv = 3)

array([0.92487479, 0.93823038, 0.92320534])

In [53]:
cross_val_score(SVC(), digits.data, digits.target, cv = 3)

array([0.96494157, 0.97996661, 0.96494157])

In [54]:
cross_val_score(RandomForestClassifier(n_estimators = 40), digits.data, digits.target, cv = 3)

array([0.92988314, 0.95993322, 0.91819699])